brain_two/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("todolists"))),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListView,
    TodoListCreateView,
    TodoListDetailView,
    TodoItemCreateView,
    TodoListDeleteView,
    TodoListUpdateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todolists"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todolist_detail"),
    path("create/", TodoListCreateView.as_view(), name="todolist_create"),
    path("items/create/", TodoItemCreateView.as_view(), name="todoitem_create"),
    path(
        "<int:pk>/delete/", TodoListDeleteView.as_view(), name="todolist_delete"
    ),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="todolist_update"
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todoitem_update",
    ),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from todos.models import TodoItem, TodoList
from django.urls import reverse_lazy

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todos/todo_lists.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/todolist_create.html"
    fields = ["name"]

    def form_valid(self, form):
        todolist = form.save(commit=False)
        todolist.save()
        return redirect("todolist_detail", pk=todolist.id)


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/todolist_detail.html"


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/todolist_delete.html"

    success_url = reverse_lazy("todolists")


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/todolist_update.html"
    fields = ["name"]

    def form_valid(self, form):
        todolist = form.save(commit=False)
        todolist.save()
        return redirect("todolist_detail", pk=todolist.id)


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/todoitem_create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def form_valid(self, form):
        todoitem = form.save(commit=False)
        todoitem.save()
        return redirect("todolist_detail", pk=todoitem.id)


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/todoitem_update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def form_valid(self, form):
        todoitem = form.save(commit=False)
        todoitem.save()
        return redirect("todolist_detail", pk=todoitem.id)

todos/templates/base.html
<!DOCTYPE html>

<html>
  <head>
    <title>Todo Lists</title>
  </head>
  <body>
    {% block main_content %} {% endblock main_content %}
  </body>
</html>

todos/templates/todos/todo_lists.html
{% extends "base.html" %} {% block main_content %}
<main>
  <h1>My Lists!</h1>
  <br />
  <a href="{% url "todolist_create" %}">Create a new list</a>
  <a href="{% url "todoitem_create" %}">Create a new item</a>
  <br>
  <table>
    {% if todolist_list|length > 0 %}
    <thead>
      <th>List Name</th>
      <th>Number of Items</th>
    </thead>
    <tbody>
        {% for list in todolist_list %}
        <tr>
          <td>
          <a href="{% url 'todolist_detail' list.pk %}">{{ list.name }}</a>
          </td>
          <td>
            {{ list.items.all|length }}
          </td>
        </tr>
        {% empty %}
        <h3>No Todo Lists</h3>
        {% endfor %}
    </tbody>
  
    {% endif %}
</main>
{% endblock main_content %}

todos/templates/todos/todoitem_create.html
{% extends "base.html" %} {% block main_content %}
<main>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Create New Item</button>
  </form>
</main>
{% endblock main_content %}

todos/templates/todos/todoitem_update.html
{% extends "base.html" %} {% block main_content %}
<main>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Update Item</button>
  </form>
</main>
{% endblock main_content %}

todos/templates/todos/todolist_create.html
{% extends "base.html" %} {% block main_content %}
<main>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Create New List</button>
  </form>
</main>
{% endblock main_content %}

todos/templates/todos/todolist_delete.html
{% extends "base.html" %} {% block main_content %}
<main>
  <form method="post">
    {% csrf_token %}
    <h3>Are you sure that you want to delete "{{ todolist.name }}"</h3>
    {{ form.as_p }}
    <button>Delete</button>
  </form>
</main>
{% endblock main_content %}

todos/templates/todos/todolist_detail.html
{% extends "base.html" %}

{% block main_content %}
<main>
    <div>
        <a href="{% url "todolists" %}">Back to List Page</a>
        <a href="{% url "todolist_update" todolist.pk %}">Edit List</a>
        <a href="{% url "todolist_delete" todolist.pk %}">Delete List</a>
    </div>
    <br>
    <h1>{{ todolist.name }}</h1>
    <table>
        <thead>
            <th>Task Name</th>
            <th>Due Date</th>
        </thead>
        <tbody>
            {% for item in todolist.items.all %}
                <tr>
                <td><a href="{% url "todoitem_update" item.pk %}">{{item.task}}</a></td>
                <td>{{item.due_date}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock main_content %}

todos/templates/todos/todolist_update.html
{% extends "base.html" %} {% block main_content %}
<main>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Update List</button>
  </form>
</main>
{% endblock main_content %}